name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

permissions:
  pull-requests: write

jobs:
  update:
    if: github.event_name != 'schedule' || github.repository == 'fisker/get-east-asian-width'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update
          branch: automated-update
          branch-suffix: timestamp
          title: Update
